// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.27.3
// source: test.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OrderCreation_Create_FullMethodName = "/OrderCreation/Create"
)

// OrderCreationClient is the client API for OrderCreation service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OrderCreationClient interface {
	Create(ctx context.Context, in *CreateOrder, opts ...grpc.CallOption) (*OrderResponse, error)
}

type orderCreationClient struct {
	cc grpc.ClientConnInterface
}

func NewOrderCreationClient(cc grpc.ClientConnInterface) OrderCreationClient {
	return &orderCreationClient{cc}
}

func (c *orderCreationClient) Create(ctx context.Context, in *CreateOrder, opts ...grpc.CallOption) (*OrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OrderResponse)
	err := c.cc.Invoke(ctx, OrderCreation_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrderCreationServer is the server API for OrderCreation service.
// All implementations must embed UnimplementedOrderCreationServer
// for forward compatibility.
type OrderCreationServer interface {
	Create(context.Context, *CreateOrder) (*OrderResponse, error)
	mustEmbedUnimplementedOrderCreationServer()
}

// UnimplementedOrderCreationServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOrderCreationServer struct{}

func (UnimplementedOrderCreationServer) Create(context.Context, *CreateOrder) (*OrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedOrderCreationServer) mustEmbedUnimplementedOrderCreationServer() {}
func (UnimplementedOrderCreationServer) testEmbeddedByValue()                       {}

// UnsafeOrderCreationServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OrderCreationServer will
// result in compilation errors.
type UnsafeOrderCreationServer interface {
	mustEmbedUnimplementedOrderCreationServer()
}

func RegisterOrderCreationServer(s grpc.ServiceRegistrar, srv OrderCreationServer) {
	// If the following call pancis, it indicates UnimplementedOrderCreationServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OrderCreation_ServiceDesc, srv)
}

func _OrderCreation_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateOrder)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderCreationServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderCreation_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderCreationServer).Create(ctx, req.(*CreateOrder))
	}
	return interceptor(ctx, in, info, handler)
}

// OrderCreation_ServiceDesc is the grpc.ServiceDesc for OrderCreation service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OrderCreation_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "OrderCreation",
	HandlerType: (*OrderCreationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _OrderCreation_Create_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "test.proto",
}
